# Generated by Django 6.0 on 2026-01-14 04:51

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(default='+996', max_length=15)),
                ('photo', models.ImageField(upload_to='users/')),
                ('city', models.CharField(max_length=50)),
                ('bio', models.TextField(max_length=500)),
                ('github_url', models.URLField()),
                ('portfolio_file', models.FileField(upload_to='portfolios/')),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('motivation_letter', models.TextField(max_length=1000)),
                ('expectations', models.TextField(max_length=300)),
                ('schedule', models.CharField(choices=[('OFFICE', 'OFFICE'), ('FLEX', 'FLEX'), ('REMOTE', 'REMOTE')], default='OFFICE', max_length=20)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=100)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
