# Generated by Django 6.0 on 2026-01-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devuser',
            name='experience_years',
            field=models.CharField(default=0),
        ),
    ]
