# Generated by Django 6.0 on 2026-01-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CineBoard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(default='Add a description to the movie'),
        ),
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='Add a description to the movie', upload_to='cineboard/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='name_film',
            field=models.CharField(default='Add a description to the movie', max_length=50, verbose_name='movie title'),
            preserve_default=False,
        ),
    ]
