# Generated by Django 6.0 on 2026-01-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='basket',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
