# Generated by Django 6.0 on 2026-01-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_basket_customer_name_basket_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='adress',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
