# Generated by Django 6.0 on 2026-01-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0003_basket_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='customer_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='basket',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
