# Generated by Django 6.0 on 2026-01-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0004_alter_basket_customer_name_alter_basket_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
