# Generated by Django 6.0 on 2026-01-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_models', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='product/')),
                ('description', models.TextField()),
                ('type_products', models.CharField(choices=[('Books', 'Books'), ('Musical instruments', 'Musical instruments'), ('Office supplies', 'Office supplies')], default='Books', max_length=50, verbose_name='category')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('warehouse', models.PositiveIntegerField(default=1, verbose_name='quantity')),
                ('manual', models.FileField(blank=True, null=True, upload_to='manuals/', verbose_name='instructions PDF')),
                ('video_review', models.URLField(blank=True, null=True, verbose_name='video review link')),
                ('product_url', models.URLField(blank=True, null=True, verbose_name='product link')),
            ],
        ),
    ]
