# Generated by Django 6.0 on 2026-01-08 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.CharField(choices=[('🤍', '🤍'), ('🤍 🤍 ', '🤍 🤍 '), ('🤍 🤍 🤍', '🤍 🤍 🤍'), ('🤍 🤍 🤍 🤍', '🤍 🤍 🤍 🤍'), ('🤍 🤍 🤍 🤍 🤍', '🤍 🤍 🤍 🤍 🤍')], default='🤍', max_length=1000)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='products.products')),
            ],
        ),
    ]
