# Generated by Django 6.0 on 2026-01-09 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_reviews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
    ]
